= Simple weather app

== Getting started

To use this app, you need to register an http://openweathermap.org/appid[API Key] on the
http://openweathermap.org/[OpenWeatherApp] service.

You can create an `application-secrets.properties` in `src/main/resources` and add your
API key there:

```
app.weather.api.key=<yourkey>
```

TIP: The `application-secrets.properties` file is referenced in the `.gitignore` of the
project so you won't commit it by mistake. The `secrets` profile is enabled by default
via the `spring.profiles.active` in the main configuration.

If you don't like specifying the key in the project directly, you can set an OS
environment property instead, something like:

```
$ EXPORT APP_WEATHER_API_KEY=<yourkey>
```

package com.example.weather;

import org.springframework.core.io.ClassPathResource;
import org.springframework.http.server.reactive.ReactorServerHttpResponse;
import org.springframework.web.reactive.result.view.AbstractUrlBasedView;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;

import java.io.IOException;
import java.util.Locale;
import java.util.Map;


public class StaticFileView extends AbstractUrlBasedView {

    public StaticFileView() {

    }

    public StaticFileView(String url) {
        this();

        setUrl(url);
    }

    @Override
    public boolean checkResourceExists(Locale locale) throws Exception {
        return true;
    }

    @Override
    protected Mono<Void> renderInternal(Map<String, Object> renderAttributes, ServerWebExchange exchange) {
        if (logger.isDebugEnabled()) {
            logger.debug("Rendering static resource [" + getUrl() + "].");
        }

//        DataBuffer dataBuffer = exchange.getResponse().bufferFactory().allocateBuffer();
//
//        try (BufferedOutputStream writer = new BufferedOutputStream(dataBuffer.asOutputStream())) {
//            writer.write(IOUtils.toByteArray(new ClassPathResource(getUrl()).getInputStream()));
//        } catch (IOException ex) {
//            String message = "Could not load resource for URL [" + getUrl() + "]";
//            return Mono.error(new IllegalStateException(message, ex));
//        } catch (Throwable ex) {
//            return Mono.error(ex);
//        }
        try {
            ClassPathResource classPathResource = new ClassPathResource(getUrl());
            return ((ReactorServerHttpResponse) exchange.getResponse()).writeWith(classPathResource.getFile(), 0, classPathResource.contentLength());
        } catch (IOException ex) {
            String message = "Could not load resource for URL [" + getUrl() + "]";
            return Mono.error(new IllegalStateException(message, ex));
        } catch (Throwable ex) {
            return Mono.error(ex);
        }
    }
}

